#
# @ Author: Marcus Vinícius Medeiros Pará 11031663
# @		 Maria Eduarda Kawakami Moreira 11218751
# @ Create Time: 2020-05-08 18:31:38
# @ Description:
#

all:
	gcc -c -Wall main.c ./lib/manage_bin/manage_bin.c ./lib/manage_csv/manage_csv.c ./lib/binarioNaTela/binarioNaTela.c ./lib/arvoreB/arvoreB.c ./lib/funcionalidades/funcionalidades.c
	gcc -Wall main.o manage_bin.o manage_csv.o binarioNaTela.o arvoreB.o funcionalidades.o -o ./main

run:
	./main
